name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build app
      run: xcodebuild -project HTTPTimer.xcodeproj -scheme HTTPTimer -destination 'platform=OS X,arch=x86_64' clean build test | xcpretty -c || true
# use on macOS >= 10.15      
#    - name: Build
#      run: swift build -v
#    - name: Run tests
#      run: swift test -v
